#!/bin/sh


##== SETUP
if [ -z "$1" ]; then
	echo "Please provide a file name to store the scanned document to. Usage: 'nopaper <filename>'"
	exit 1
fi
PDF_FILE=$1


##== SCAN
echo "Scanning document..."
SCANTO=$(mktemp --suffix=".pdf" --tmpdir=.)
if [ -f $PDF_FILE ]; then
    echo "Appending to ${PDF_FILE}"
    NAPS2.Console.exe --enableocr -p document.flatbed -o $SCANTO --force -i $PDF_FILE
else
    NAPS2.Console.exe --enableocr -p document.flatbed -o $SCANTO --force
fi


##== COMPRESS & PDF/A
sleep 1
echo "Compressing document..."
PDF_BEFORE_A=$SCANTO
pdftops $PDF_BEFORE_A - | gs \
    -dPDFA=2 \
    -dBATCH \
    -dNOPAUSE \
    -sProcessColorModel=DeviceCMYK \
    -sDEVICE=pdfwrite \
    -dPDFSETTINGS=/printer \
    -r1200 \
    -sPDFACompatibilityPolicy=1 \
    -sOutputFile=$PDF_FILE \
    -

##== CLEANUP
rm $SCANTO

echo "Finished scanning document to ${PDF_FILE}"